name: Deploy Web App to GitHub Pages

on:
  push:
    branches:
      - main  # Déclenche le workflow sur chaque push vers la branche 'main'
  workflow_dispatch:  # Permet d'exécuter manuellement le workflow via l'onglet Actions

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de construction du projet
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout le code source du dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # Vérifier si package.json existe, sinon créer un package.json et installer les dépendances de base
      - name: Initialize project and install dependencies
        run: |
          # Initialiser un projet npm avec un package.json minimal
          npm init -y
          
          # Installer les dépendances nécessaires
          npm install react react-dom react-scripts vue vue-router axios bootstrap

          # Créer un fichier index.html minimal dans le dossier public si il n'existe pas
          mkdir -p public
          echo '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>React App</title></head><body><div id="root"></div></body></html>' > public/index.html

      # Ajouter un script "build" au package.json
      - name: Add build script to package.json
        run: |
          # Ajouter le script build nécessaire pour React
          jq '.scripts.build="react-scripts build"' package.json > temp.json && mv temp.json package.json

      # Construire l'application (ceci génère les fichiers de build)
      - name: Build the project
        run: npm run build  # Ce script utilise 'react-scripts build' pour créer le build React

      # Télécharger l'artefact pour le déploiement
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build  # Utilisez le dossier 'build' généré par React

  # Job de déploiement sur GitHub Pages
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ce job dépend du job "build" pour fonctionner
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}  # URL de la page GitHub Pages

    steps:
      # Checkout du code pour déployer sur la branche 'main'
      - name: Checkout repository again
        uses: actions/checkout@v4
        with:
          ref: main  # On s'assure d'être sur la branche main pour le déploiement

      # Déployer l'artefact sur GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages  # Déployer sur la branche gh-pages au lieu de main (commonly used for GitHub Pages)
