name: Deploy Web App to GitHub Pages

on:
  push:
    branches:
      - main  # Déclenche le workflow sur chaque push vers la branche 'main'
  workflow_dispatch:  # Permet d'exécuter manuellement le workflow via l'onglet Actions

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de construction du projet
  build:
    runs-on: ubuntu-latest
    steps:
      # Récupère le code source du dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # Initialisation du projet npm et installation des packages de base
      - name: Initialize project and install dependencies
        run: |
          # Initialiser un projet npm avec un package.json minimal
          npm init -y
          
          # Installer React et React-DOM
          npm install react react-dom react-scripts
          
          # Installer Vue et Vue Router
          npm install vue vue-router
          
          # Installer Axios pour les appels HTTP
          npm install axios
          
          # Installer Bootstrap pour les styles
          npm install bootstrap

      # Installer toutes les dépendances après l'ajout dans le package.json
      - name: Install dependencies
        run: npm install

      # Construire l'application (pour un projet React ou autre)
      - name: Build the project
        run: npm run build

      # Exporter le projet (si vous utilisez Next.js ou un autre générateur statique)
      - name: Export the site (if using Next.js)
        run: npm run export || echo "No export command found"

      # Télécharger l'artefact pour le déploiement
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out  # Indique le dossier des fichiers statiques générés

  # Job de déploiement sur GitHub Pages
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ce job dépend du job "build" pour fonctionner
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}  # URL de la page GitHub Pages

    steps:
      # Checkout the repository again to deploy to the same branch
      - name: Checkout repository again
        uses: actions/checkout@v4
        with:
          ref: main  # S'assurer qu'on est bien sur la branche main

      # Déployer l'artefact dans la racine de la branche 'main'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          branch: main  # Indique qu'on déploie sur la branche 'main'
