## Project
# GitHub Actions workflow
# Auteur : ACOMDIR
# Url contact: https://www.facebook.com/acomdir/
# Please come vote my page Facebook to support me in the development of this open source project.

name: ci-build-gh-pages

on:
  push:
    branches:
      - "main"  # Déclenche le workflow sur un push vers la branche 'main'
  pull_request:
    branches:
      - "main"  # Déclenche le workflow sur un pull request vers la branche 'main'
  workflow_dispatch:  # Permet de déclencher manuellement le workflow

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # Exécution sur un environnement Ubuntu

    steps:
      # 1. Vérifier le code source
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configurer l'identité Git pour les commits
      - name: Set up Git identity
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      # 3. Vérifier si la branche gh-pages existe, sinon la créer
      - name: Check if gh-pages exists
        run: |
          git fetch origin
          if ! git show-ref --quiet refs/heads/gh-pages; then
            echo "La branche gh-pages n'existe pas, création de la branche."
            git checkout --orphan gh-pages  # Créer une nouvelle branche orpheline
            git rm -rf .  # Supprimer tous les fichiers (car la branche est orpheline)
            git commit --allow-empty -m "Initial commit for gh-pages"
            git push origin gh-pages  # Pousser la branche gh-pages sur le dépôt distant
          else
            echo "La branche gh-pages existe déjà."
          fi

      # 6. Exécuter des tests ou construire votre projet
      - name: Run tests or build
        run: |
          # Remplacer par la commande de build ou de test de votre projet

      # 7. Déployer sur GitHub Pages (via peaceiris/actions-gh-pages)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Utiliser le token GitHub pour l'authentification
          branch: gh-pages  # Branche de destination
          folder: build  # Le dossier à déployer (modifiez-le en fonction de votre configuration)
          clean: true  # Nettoie le répertoire gh-pages avant le déploiement

      # Optionnel : Si vous souhaitez notifier ou exécuter d'autres actions après le déploiement
      - name: Notify deployment success
        run: echo "Deployment to gh-pages successful!"

      # Récupérer l'URL de la page déployée et afficher un lien cliquable
      - name: Provide link to deployed site
        run: |
          echo "Site déployé avec succès ! Vous pouvez accéder à la page à l'adresse suivante :"
          echo "${{ steps.deployment.outputs.page_url }}"
